name: Build and Test (Maven Multi-Module)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v3

      - name: ☕ Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: 🧪 Build with Maven
        run: mvn -B clean verify

      - name: ✅ Test summary
        if: success()
        run: echo "✔ Build and tests passed."
